version: '3.8'

services:
  # Бэкенд на Django
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/ai_db
      - OLLAMA_CHAT_URL=http://ollama:11434/api/chat

    depends_on:
      - db
      - ollama

  # База данных
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ai_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  # ИИ-движок
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  pg_data:
  ollama_data: