# Generated by Django 5.2.8 on 2026-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('hr', 'HR'), ('aho', 'АХО'), ('it', 'ИТ'), ('finance', 'Финансы'), ('legal', 'Юридический отдел'), ('young_talents', 'Направление молодых талантов'), ('project_office', 'Проектный офис')], default='hr', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('team_lead', 'Руководитель команды'), ('admin', 'Администратор')], default='employee', max_length=20, verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
