# Generated by Django 6.0.5 on 2026-05-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('department', models.CharField(choices=[('HR', 'HR'), ('AXO', 'АХО'), ('IT', 'ИТ'), ('FINANCE', 'Финансы'), ('LEGAL', 'Юридический отдел'), ('TALENTS', 'Направление молодых талантов'), ('PMO', 'Проектный офис')], max_length=50, verbose_name='Отдел')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий')], default='MEDIUM', max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('REVIEW', 'На согласовании'), ('COMPLETED', 'Выполнена'), ('OVERDUE', 'Просрочена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('period', models.CharField(choices=[('YEAR', 'Год'), ('QUARTER', 'Квартал'), ('MONTH', 'Месяц'), ('WEEK', 'Неделя')], max_length=20, verbose_name='Горизонт планирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('parent_task', models.ForeignKey(blank=True, help_text='Связь: Годовая цель -> Квартальная задача -> Месячная задача -> Недельная задача', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.task', verbose_name='Родительская задача')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
